"""create companies, jobs and fetch_runs tables

Revision ID: 1b5f9fd31c21
Revises: 
Create Date: 2026-10-02 01:14:37.453037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b5f9fd31c21'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('size_category', sa.String(length=20), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('countries', sa.JSON(), nullable=False),
    sa.Column('careers_url', sa.String(length=500), nullable=True),
    sa.Column('ats_type', sa.String(length=30), nullable=True),
    sa.Column('ats_token', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('added_by_user_id', sa.Integer(), nullable=True),
    sa.Column('baseline_done', sa.Boolean(), nullable=False),
    sa.Column('last_fetch_ok_at', sa.DateTime(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('slug', name=op.f('uq_companies_slug'))
    )
    op.create_table('fetch_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('jobs_returned', sa.Integer(), nullable=True),
    sa.Column('new_jobs', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_fetch_runs_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fetch_runs'))
    )
    with op.batch_alter_table('fetch_runs', schema=None) as batch_op:
        batch_op.create_index('ix_fetch_runs_company_started', ['company_id', 'started_at'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('ats_type', sa.String(length=30), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('location_raw', sa.String(length=500), nullable=True),
    sa.Column('country_codes', sa.JSON(), nullable=False),
    sa.Column('description_text', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('missing_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('prefilter_status', sa.String(length=20), nullable=False),
    sa.Column('prefilter_reason', sa.String(length=200), nullable=True),
    sa.Column('analysis_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_jobs_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('company_id', 'external_id', name='uq_jobs_company_external_id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_analysis_status', ['analysis_status'], unique=False)
        batch_op.create_index('ix_jobs_fingerprint', ['fingerprint'], unique=False)
        batch_op.create_index('ix_jobs_first_seen_at', ['first_seen_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_first_seen_at')
        batch_op.drop_index('ix_jobs_fingerprint')
        batch_op.drop_index('ix_jobs_analysis_status')

    op.drop_table('jobs')
    with op.batch_alter_table('fetch_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_fetch_runs_company_started')

    op.drop_table('fetch_runs')
    op.drop_table('companies')
    # ### end Alembic commands ###
