"""add jobs matched_at

Revision ID: 21474a4985dc
Revises: 58f90bc1d725
Create Date: 2026-10-09 12:20:27.769343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21474a4985dc'
down_revision: Union[str, Sequence[str], None] = '58f90bc1d725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Empty for every existing job: the jobs already analysed are matched on the next run.
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matched_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('matched_at')

    # ### end Alembic commands ###
