"""add duplicate link to jobs

Revision ID: 2d223caf33cf
Revises: 1b5f9fd31c21
Create Date: 2026-10-03 13:55:14.133741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d223caf33cf'
down_revision: Union[str, Sequence[str], None] = '1b5f9fd31c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duplicate_of_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_jobs_duplicate_of_id_jobs'), 'jobs', ['duplicate_of_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_jobs_duplicate_of_id_jobs'), type_='foreignkey')
        batch_op.drop_column('duplicate_of_id')

    # ### end Alembic commands ###
