"""add job analysis and llm usage

Revision ID: 3d87c1822ecf
Revises: fdda4092aa23
Create Date: 2026-10-07 21:33:24.227078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d87c1822ecf'
down_revision: Union[str, Sequence[str], None] = 'fdda4092aa23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('est_cost_usd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('day', name=op.f('pk_llm_usage'))
    )
    op.create_table('job_analysis',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('countries', sa.JSON(), nullable=False),
    sa.Column('cities', sa.JSON(), nullable=False),
    sa.Column('work_mode', sa.String(length=20), nullable=True),
    sa.Column('seniority', sa.String(length=20), nullable=True),
    sa.Column('is_graduate_scheme', sa.Boolean(), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('experience_mandatory', sa.Boolean(), nullable=False),
    sa.Column('required_languages', sa.JSON(), nullable=False),
    sa.Column('role_families', sa.JSON(), nullable=False),
    sa.Column('matched_custom_roles', sa.JSON(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('min_degree', sa.String(length=20), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('summary', sa.String(length=200), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('analysed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_analysis_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', name=op.f('pk_job_analysis'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_analysis')
    op.drop_table('llm_usage')
    # ### end Alembic commands ###
