"""add matches and jobs became_new_at

Revision ID: 58f90bc1d725
Revises: 3d87c1822ecf
Create Date: 2026-10-09 11:09:20.445045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58f90bc1d725'
down_revision: Union[str, Sequence[str], None] = '3d87c1822ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('scored_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_matches_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_matches_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches')),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_matches_user_id_job_id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index('ix_matches_job_id', ['job_id'], unique=False)

    # Existing jobs became new when they were first seen. The column is added empty, filled in,
    # and only then made required: a required column can't be added to rows that already exist.
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('became_new_at', sa.DateTime(), nullable=True))
    op.execute('UPDATE jobs SET became_new_at = first_seen_at')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('became_new_at', existing_type=sa.DateTime(), nullable=False)
        batch_op.create_index('ix_jobs_became_new_at', ['became_new_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_became_new_at')
        batch_op.drop_column('became_new_at')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index('ix_matches_job_id')

    op.drop_table('matches')
    # ### end Alembic commands ###
