"""add users, user profiles and company preferences

Revision ID: fdda4092aa23
Revises: 2d223caf33cf
Create Date: 2026-10-07 18:19:24.508579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdda4092aa23'
down_revision: Union[str, Sequence[str], None] = '2d223caf33cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_users_telegram_id'))
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('custom_roles', sa.JSON(), nullable=False),
    sa.Column('countries', sa.JSON(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('preferred_industries', sa.JSON(), nullable=False),
    sa.Column('excluded_industries', sa.JSON(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('highest_degree', sa.String(length=20), nullable=True),
    sa.Column('include_internships', sa.Boolean(), nullable=False),
    sa.Column('alert_style', sa.String(length=20), nullable=False),
    sa.Column('transfer_boost', sa.Boolean(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_profiles'))
    )
    op.create_table('user_company_prefs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('never_miss', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_user_company_prefs_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_company_prefs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'company_id', name=op.f('pk_user_company_prefs'))
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_companies_added_by_user_id_users'), 'users', ['added_by_user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_companies_added_by_user_id_users'), type_='foreignkey')

    op.drop_table('user_company_prefs')
    op.drop_table('user_profiles')
    op.drop_table('users')
    # ### end Alembic commands ###
